type: custom:stack-in-card
cards:
  - type: horizontal-stack
    cards:
      - type: custom:mushroom-entity-card
        entity: sensor.livingroom_temperature
        name: Temperatur
        icon_color: red
      - type: custom:mushroom-entity-card
        entity: sensor.livingroom_humidity
        name: Luftfeuchtigkeit
  - type: custom:mini-graph-card
    entities:
      - entity: sensor.livingroom_temperature
        color: red
      - entity: sensor.livingroom_humidity
        y_axis: secondary
    group: true
    points_per_hour: 1
    show:
      icon: false
      legend: false
      name: false
      state: false
